name: Build
on:
  push:
    branches:
      - "master"
jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Build for Linux
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
      - name: Install assets
        run: npm install
      - name: Build
        run: npm run dist:linux
        env:
          GH_TOKEN: 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
  build-windows:
    runs-on: windows-latest
    name: Build for Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
      - name: Install assets
        run: npm install
      - name: Build
        run: npm run dist:win
        env:
          GH_TOKEN: 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
